services:
  database:
    container_name: go-api-boilerplate-database
    image: postgres:18.6-alpine3.24
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql

volumes:
  database:
