FROM golang:1.23.0-alpine3.20 AS builder

ARG BUILD_ID
LABEL stage=builder
LABEL build=$BUILD_ID

WORKDIR /app
COPY . .

RUN go mod download
RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s -buildid=" -trimpath -o ./bin/api ./cmd/api/main.go

# ----------------------------

FROM gcr.io/distroless/static-debian11

WORKDIR /app
COPY --from=builder /app/bin/api .

ENTRYPOINT [ "./api" ]
