services:
  database:
    container_name: go-api-boilerplate-database
    image: postgres:17.2-alpine3.20
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
